<a href="https://colab.research.google.com/github/lohith-kandibanda/Machine_learning_subj/blob/main/lab-session-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Function to count vowels and consonants in a string
def count_vowels_consonants(Inp_Str):
    vowel_count = 0  # Initialize vowel count
    consonant_count = 0  # Initialize consonant count
    str = Inp_Str.lower()  # Convert input to lowercase for easy comparison
    
    for char in str:  # Iterate through each character in the string
        if char in {'a', 'e', 'i', 'o', 'u'}:  # Check if it's a vowel
            vowel_count += 1
        elif char in {'b', 'c', 'd', 'f', 'g', 'h' , 'j' , 'k' , 'l', 'm', 'n', 'p', 'q', 'r', 's', 't' , 'v', 'w' , 'x' , 'y' , 'z'}:  # Check if it's a consonant
            consonant_count += 1
    
    return (vowel_count, consonant_count)  # Return the counts

# Get input and call the function
str = input("Enter a string: ")
v, c = count_vowels_consonants(str)  # Store the results
print(v, c)  # Print vowel and consonant counts


Enter a string:  abcdefGHIJKLMNO


4 11


In [ ]:
import numpy as np

# Function to compute the product of two matrices using numpy
def Product_AB(A, B):
   return np.dot(A, B)  # Perform matrix multiplication

# Input for matrix dimensions
print("Enter the size of row of matrix 1")
r1 = int(input())
print("Enter the size of column of matrix 1")
c1 = int(input())
print("Enter the size of row of matrix 2")
r2 = int(input())
print("Enter the size of column of matrix 2")
c2 = int(input())

matrice1 = []
matrice2 = []

# Loop to take input for the first matrix
print('Enter elements for matrix 1:')
for j in range(r1):  # Iterate over rows
  a = []
  for i in range(c1):  # Iterate over columns
    a.append(int(input()))
  matrice1.append(a)

# Loop to take input for the second matrix
print('Enter elements for matrix 2:')
for j in range(r2):  # Iterate over rows
  a = []
  for i in range(c2):  # Iterate over columns
    a.append(int(input()))
  matrice2.append(a)

# Check if matrix multiplication is possible (columns of A == rows of B)
if c1 == r2:
  print(Product_AB(matrice1, matrice2))  # Call the function to multiply the matrices
else:
  print("Error: Matrix dimensions are incompatible for multiplication")


enter the size of row of matrice 1
3
enter the size of column of matrice 1
3
enter the size of row of matrice 2
3
enter the size of column of matrice 2
3
enter
1
2
3
1
2
3
1
2
3
enter
1
2
3
1
2
3
1
2
3
[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [ ]:
# Function to find common elements between two lists
def common_elements(lst1, lst2):
  count = 0  # Initialize counter for common elements
  # Loop through the first list
  for i in lst1:
    if i in lst2:  # Check if element exists in the second list
      count += 1  # Increment counter if common element is found
  return count  # Return the count of common elements

# Input for the length of the lists
print("Enter the length of the lists:")
n = int(input())

lst1 = []
lst2 = []

# Loop to take input for the first list
print("Enter the elements of list 1:")
for i in range(n):
  a = int(input("Enter: "))  # Input for list 1 elements
  lst1.append(a)

# Loop to take input for the second list
print("Enter the elements of list 2:")
for i in range(n):
  b = int(input("Enter: "))  # Input for list 2 elements
  lst2.append(b)

# Call the function to find common elements and display the result
c = common_elements(lst1, lst2)
print("Common elements in the lists are:", c)


enter the len of lsts
4
enter the elements of list1
enter1
enter2
enter3
enter4
enter the elements of list2
enter1
enter2
enter3
enter4
common elements in lists are  4


In [ ]:
import numpy as np

# Function to transpose a matrix
def transpose(A):
  np_matrix = np.array(A)  # Convert the input list to a numpy array
  transposed = np_matrix.T  # Transpose the matrix
  return transposed  # Return the transposed matrix

# Input for matrix dimensions
print("Enter the size of row of matrix 1:")
r1 = int(input())
print("Enter the size of column of matrix 1:")
c1 = int(input())

matrice1 = []

# Loop to take input for the matrix
print('Enter the elements of the matrix:')
for j in range(r1):  # Iterate over rows
  a = []
  for i in range(c1):  # Iterate over columns
    a.append(int(input()))  # Input for each element of the matrix
  matrice1.append(a)

# Call the transpose function and display the result
B = transpose(matrice1)
print(B)  # Print the transposed matrix


enter the size of row of matrice 1
3
enter the size of column of matrice 1
3
enter
1
2
3
2
4
5
7
5
2
[[1 2 7]
 [2 4 5]
 [3 5 2]]
